// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTd00EX1h9W3HsbY1zRAaDMpEzIxiAAI4',
    appId: '1:882477402082:web:1f6a96c480a3c8414e1bbb',
    messagingSenderId: '882477402082',
    projectId: 'lab4-63eb3',
    authDomain: 'lab4-63eb3.firebaseapp.com',
    storageBucket: 'lab4-63eb3.appspot.com',
    measurementId: 'G-YZ32FJXR3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NrCyVi8n8KXkqLanPozhqL5pinnvOt4',
    appId: '1:882477402082:android:d6d85cc053f8e9304e1bbb',
    messagingSenderId: '882477402082',
    projectId: 'lab4-63eb3',
    storageBucket: 'lab4-63eb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5hLC-2eCo0aoS_bH9k5Uk8_8tDlJMYNs',
    appId: '1:882477402082:ios:50e1aa70b97c938a4e1bbb',
    messagingSenderId: '882477402082',
    projectId: 'lab4-63eb3',
    storageBucket: 'lab4-63eb3.appspot.com',
    iosClientId: '882477402082-9qors4jsof5f9v06oh80npkkpsrd290q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5hLC-2eCo0aoS_bH9k5Uk8_8tDlJMYNs',
    appId: '1:882477402082:ios:50e1aa70b97c938a4e1bbb',
    messagingSenderId: '882477402082',
    projectId: 'lab4-63eb3',
    storageBucket: 'lab4-63eb3.appspot.com',
    iosClientId: '882477402082-9qors4jsof5f9v06oh80npkkpsrd290q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
